"""empty message

Revision ID: 9529a0146215
Revises: 86fb70c2d92a
Create Date: 2020-07-10 21:04:48.901181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9529a0146215'
down_revision = '86fb70c2d92a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todoList',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('listId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todoList', ['listId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    #op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'listId')
    op.drop_table('todoList')
    # ### end Alembic commands ###
