"""empty message

Revision ID: a5a0fe05bd34
Revises: 9529a0146215
Create Date: 2020-07-10 21:15:24.510594

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5a0fe05bd34'
down_revision = '9529a0146215'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todolist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('listId', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'todolist', ['listId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.drop_column('todos', 'listId')
    op.drop_table('todolist')
    # ### end Alembic commands ###
