"""empty message

Revision ID: f22ceb1cd7c0
Revises: a5a0fe05bd34
Create Date: 2020-07-10 21:18:30.284907

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22ceb1cd7c0'
down_revision = 'a5a0fe05bd34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.drop_constraint('todos_listId_fkey', 'todos', type_='foreignkey')
    op.create_foreign_key(None, 'todos', 'todolist', ['list_id'], ['id'])
    op.drop_column('todos', 'listId')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('listId', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'todos', type_='foreignkey')
    op.create_foreign_key('todos_listId_fkey', 'todos', 'todolist', ['listId'], ['id'])
    op.drop_column('todos', 'list_id')
    # ### end Alembic commands ###
